<button id="button">
    <span><?= $block->escapeHtml(__('Best Seller')) ?></span>
</button>

<div id="modal">
    <div class="modal-body-content">
        <?php
            $status = $block->isEnable();
            $items = $block->getProductBestSeller();
            $item_config = number_format($block->getNumberBestSellerConfig());
            $currencySymbols = $block->getStoreCurrency();
            $count = 0;
        ?>
        <?php
            if ($status) {
                echo "<ul class='bestseller'>";
                foreach ($items as $item) {
                    $count++;
                    $product_url = $block->getProductUrl($item->getProductId());
                    echo "<li id='bestseller-item'>";
                    echo "<a href=". $product_url . " ><img src=" . $block->getImageBestSeller($item->getProductId()) . "></a>";
                    echo "<a href=". $product_url . " ><p class='bestseller-name'>" . $item->getProductName() . "</p></a>";
                    echo "<p class='bestseller-price'>" .$currencySymbols. number_format($item->getProductPrice(),2) . "</p>";
                    echo "<p class='bestseller-order'>" . 'Ordered: ' . number_format($item->getQtyOrdered()) . "</p>";
                    echo "</li>";
                }
                echo '</ul>';
                echo "<div class='showmore'>";
                echo "<button id='show-more' onclick="."myFunction()".">Show more</button>";
                echo '</div>';
            }
        ?>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Best Seller',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal'));
        $("#button").click(function() {
            $('#modal').modal('openModal');
        });

        var item_config = "<?= $item_config ?>";
        var item_count = "<?= $count ?>";
        var signal = item_count - item_config;
        console.log(signal);
        if(item_count > item_config) {
            for (i = 1; i <= signal; i++) {
                $( "#bestseller-item:nth-last-child("+i+")").css( "display", "none" );
            }
        }else{
            $( "#show-more" ).remove();
        }
        $('#show-more').click(function() {
            for (i = 1; i <= signal; i++) {
                $( "#bestseller-item:nth-last-child("+i+")").css( "display", "flex" );
            }
            $( "#show-more" ).remove();
        });
        
    });
</script>
