<?php
    $status = $block->isEnable();
    $item_config = number_format($block->getNumberBestSellerConfig());
    $items = $block->getProductBestSeller($item_config);
    $currencySymbols = $block->getStoreCurrency();
    $count = 0;
?>
<?php
    if ($status) {
        echo "<h2 class='bestseller-title'>Best Seller</h2>";
        echo "<ul class='bestseller'>";
        foreach ($items as $item) {
            $count++;
            $product_url = $block->getProductUrl($item->getProductId());
            echo "<li id='bestseller-item'>";
            echo "<a href=". $product_url . " ><img src=" . $block->getImageBestSeller($item->getProductId()) . "></a>";
            echo "<a href=". $product_url . " ><p class='bestseller-name'>" . $item->getProductName() . "</p></a>";
            echo "<p class='bestseller-price'>" .$currencySymbols. number_format($item->getProductPrice(),2) . "</p>";
            echo "<p class='bestseller-order'>" . 'Ordered: ' . number_format($item->getQtyOrdered()) . "</p>";
            echo "</li>";
        }
        echo '</ul>';
        echo "<div class='showmore'>";
        echo "<button id='show-more'".">Show more</button>";
        echo '</div>';
    }
?>

<script>
    require(["jquery"], function($){
        var item_config = "<?= $item_config ?>";    
        var item_count = "<?= $count ?>";
        var signal = item_count - item_config;
        var items = "<?= json_encode($block->getProductBestSeller($item_config)) ?>";  

        $('#show-more').click(function() {
            console.log("<?= "aaa" . json_encode($block->getProductBestSeller($item_config)) ?>");
            // $.each( items, function( index, value ) {
            //     alert( index + ": " + value );
            // });
            // $( "#show-more" ).remove();
        });
    });
</script>

