<?php
    $status = $block->isEnable();
    $item_config = number_format($block->getNumberBestSellerConfig());
    $items = $block->getProductBestSeller($item_config,0);
    $currencySymbols = $block->getStoreCurrency();
    $count = 0;
?>
<?php
    if ($status) {
        echo "<h2 class='bestseller-title'>Best Seller</h2>";
        echo "<ul class='bestseller'>";
        foreach ($items as $item) {
            $count++;
            $product_url = $block->getProductUrl($item->getProductId());
            echo "<li id='bestseller-item'>";
            echo "<a href=". $product_url . " ><img src=" . $block->getImageBestSeller($item->getProductId()) . "></a>";
            echo "<a href=". $product_url . " ><p class='bestseller-name'>" . $item->getProductName() . "</p></a>";
            echo "<p class='bestseller-price'>" .$currencySymbols. number_format($item->getProductPrice(),2) . "</p>";
            echo "<p class='bestseller-order'>" . 'Ordered: ' . number_format($item->getQtyOrdered()) . "</p>";
            echo "</li>";
        }
        echo '</ul>';
        echo "<div class='showmore'>";
        echo "<button id='show-more'".">Show more</button>";
        echo '</div>';
    }
    // echo "<pre>";
    // print_r($items->getData());
    
?>

<script type="text/x-magento-init">
    {
        "#show-more": {
            "AHT_BestSeller/js/custom": {
                "itemCount": <?= $item_config  ?>,
                "item": <?= number_format($block->getNumberPageSize()) ?>,
                "url": "bestseller/index/bestSeller"
            } 
        }
    }
</script>

